# Example

In [1]:
savefolder = '/Users/gitaepark/Downloads'
model_name = "mallet_0.05_0.5_30_0.05_0.01"

In [2]:
import lda_eval_lib
import pandas as pd
import os

In [3]:
# Load a test file
package_path = os.path.dirname(lda_eval_lib.__file__)
data_path = os.path.join(package_path, 'test_text.pkl')
item1a = pd.read_pickle(data_path)
tokenized_text = item1a['text4LDA']

### LDA run (gensim LDA and modified mallet wrapper)

In [4]:

# Set parameters
minpc = 0.05 
maxpc = 0.5
alpha = 0.05
beta = 0.01
ntopics = 30

# path to mallet bin
mallet_path = '/Users/mallet-2.0.8/bin/mallet'

In [5]:
lda_eval_lib.lda_model.lda_run(tokenized_text, minpc, maxpc, alpha, beta, ntopics, mallet_path, savefolder, gensimpasses = 5, gensimiterations = 10, malletiterations = 100)

 - modelling  gensim_0.05_0.5_30_0.05_0.01
model saved: /Users/gitaepark/Downloads/gensim_0.05_0.5_30_0.05_0.01
 - modelling  mallet_0.05_0.5_30_0.05_0.01

Mallet LDA: 30 topics, 5 topic bits, 11111 topic mask
Data loaded.
max tokens: 3423
total tokens: 512341
<10> LL/token: -8.72978
<20> LL/token: -8.05332
<30> LL/token: -7.88945
<40> LL/token: -7.81607
<50> LL/token: -7.76683
<60> LL/token: -7.73101
<70> LL/token: -7.70768
<80> LL/token: -7.68756
<90> LL/token: -7.67148
<100> LL/token: -7.65641

Total time: 4 seconds

model saved: /Users/gitaepark/Downloads/mallet_0.05_0.5_30_0.05_0.01

In [6]:
model_name = "gensim_0.05_0.5_30_0.05_0.01"

# Load the stored model
lda_model, textbeforetokenization, tokenized_text, corpus, id2word = lda_eval_lib.util.load_lda_run(savefolder,model_name)

# lda_model is other gensim.lda object or gensim.mallet object
lda_model.show_topics(num_topics=-1)

[(0,
  '0.013*"indemnification" + 0.013*"raw" + 0.008*"agreement" + 0.008*"letter" + 0.007*"ruling" + 0.007*"opinion" + 0.007*"separation" + 0.007*"monetary" + 0.006*"secrets" + 0.006*"audits"'),
 (1,
  '0.023*"digital" + 0.016*"advertising" + 0.011*"talent" + 0.011*"incorporated" + 0.010*"quickly" + 0.010*"reference" + 0.009*"raw" + 0.009*"content" + 0.008*"grow" + 0.008*"heading"'),
 (2,
  '0.012*"patents" + 0.009*"patent" + 0.006*"injury" + 0.006*"post" + 0.005*"monetary" + 0.005*"infringement" + 0.005*"ventures" + 0.005*"practice" + 0.004*"enforce" + 0.004*"hazardous"'),
 (3,
  '0.016*"advertising" + 0.013*"forum" + 0.013*"stockholders" + 0.012*"media" + 0.009*"directors" + 0.008*"exclusive" + 0.007*"provision" + 0.007*"libor" + 0.007*"consent" + 0.007*"bylaws"'),
 (4,
  '0.056*"oil" + 0.054*"gas" + 0.028*"drilling" + 0.016*"reserves" + 0.012*"rigs" + 0.009*"exploration" + 0.009*"wells" + 0.008*"water" + 0.008*"properties" + 0.008*"commodity"'),
 (5,
  '0.019*"water" + 0.017*"brands" + 0.016*"raw" + 0.012*"beverage" + 0.010*"class" + 0.010*"packaging" + 0.010*"consumers" + 0.010*"glass" + 0.009*"controlled" + 0.007*"retailers"'),
 (6,
  '0.037*"loans" + 0.020*"libor" + 0.017*"loan" + 0.017*"real" + 0.016*"estate" + 0.015*"banking" + 0.015*"bank" + 0.013*"banks" + 0.010*"deposits" + 0.009*"mortgage"'),
 (7,
  '0.087*"stores" + 0.070*"retail" + 0.061*"inventory" + 0.040*"retailers" + 0.038*"lease" + 0.037*"store" + 0.035*"space" + 0.023*"online" + 0.018*"real" + 0.017*"goods"'),
 (8,
  '0.058*"clients" + 0.020*"client" + 0.009*"solutions" + 0.005*"fees" + 0.005*"underwriting" + 0.005*"firms" + 0.004*"disaster" + 0.004*"brokerage" + 0.004*"administration" + 0.004*"consulting"'),
 (9,
  '0.017*"pension" + 0.007*"similarly" + 0.006*"incidents" + 0.006*"internet" + 0.006*"introduce" + 0.006*"communications" + 0.006*"emerging" + 0.005*"incentives" + 0.005*"disrupted" + 0.005*"advanced"'),
 (10,
  '0.023*"transformation" + 0.018*"ventures" + 0.013*"inventory" + 0.012*"warranty" + 0.010*"devote" + 0.009*"excess" + 0.009*"refer" + 0.009*"segments" + 0.009*"introductions" + 0.009*"decreased"'),
 (11,
  '0.017*"cards" + 0.014*"card" + 0.013*"member" + 0.013*"members" + 0.011*"regulators" + 0.010*"brand" + 0.010*"acceptance" + 0.008*"travel" + 0.006*"account" + 0.006*"discount"'),
 (12,
  '0.053*"aircraft" + 0.031*"fuel" + 0.028*"carriers" + 0.024*"air" + 0.023*"travel" + 0.021*"airline" + 0.015*"airlines" + 0.009*"agreement" + 0.009*"traffic" + 0.008*"aviation"'),
 (13,
  '0.015*"ingredients" + 0.012*"water" + 0.010*"food" + 0.009*"agricultural" + 0.009*"commodity" + 0.009*"packaging" + 0.008*"beverage" + 0.008*"commodities" + 0.007*"agriculture" + 0.007*"deterioration"'),
 (14,
  '0.010*"curve" + 0.009*"section" + 0.008*"fair" + 0.008*"valuation" + 0.008*"denominated" + 0.007*"lien" + 0.007*"deferred" + 0.006*"hedging" + 0.005*"release" + 0.005*"margin"'),
 (15,
  '0.025*"research" + 0.014*"raw" + 0.010*"manufacture" + 0.010*"engineering" + 0.010*"design" + 0.008*"specialized" + 0.008*"improper" + 0.008*"single" + 0.008*"misappropriation" + 0.008*"infringement"'),
 (16,
  '0.057*"vehicles" + 0.030*"vehicle" + 0.021*"rental" + 0.014*"fleet" + 0.012*"locations" + 0.008*"mobility" + 0.007*"operators" + 0.007*"fuel" + 0.007*"travel" + 0.007*"backed"'),
 (17,
  '0.048*"institutions" + 0.048*"institution" + 0.039*"participate" + 0.036*"title" + 0.030*"iv" + 0.018*"education" + 0.015*"aid" + 0.013*"lose" + 0.013*"repayment" + 0.012*"defense"'),
 (18,
  '0.030*"segment" + 0.030*"note" + 0.017*"compared" + 0.017*"partially" + 0.016*"fair" + 0.015*"continuing" + 0.015*"unit" + 0.015*"pension" + 0.015*"recognized" + 0.013*"versus"'),
 (19,
  '0.020*"care" + 0.019*"medical" + 0.018*"clinical" + 0.014*"healthcare" + 0.014*"reimbursement" + 0.010*"approval" + 0.009*"devices" + 0.007*"clearance" + 0.007*"manufacture" + 0.007*"manufacturers"'),
 (20,
  '0.031*"software" + 0.020*"solutions" + 0.013*"cloud" + 0.011*"licenses" + 0.008*"distributors" + 0.008*"incident" + 0.007*"technical" + 0.006*"license" + 0.006*"incidents" + 0.006*"ccpa"'),
 (21,
  '0.014*"profits" + 0.013*"budget" + 0.012*"productivity" + 0.010*"segment" + 0.009*"raw" + 0.009*"suspension" + 0.009*"improper" + 0.008*"defense" + 0.008*"contractor" + 0.008*"packaging"'),
 (22,
  '0.054*"shares" + 0.023*"properties" + 0.020*"preferred" + 0.019*"holders" + 0.017*"shareholders" + 0.012*"voting" + 0.010*"vote" + 0.010*"distributions" + 0.009*"covenants" + 0.009*"default"'),
 (23,
  '0.010*"fuel" + 0.009*"pension" + 0.009*"currencies" + 0.009*"goods" + 0.007*"wage" + 0.007*"employment" + 0.006*"located" + 0.006*"temporary" + 0.006*"shortages" + 0.006*"engines"'),
 (24,
  '0.015*"raw" + 0.010*"dealers" + 0.008*"hazardous" + 0.008*"patents" + 0.007*"manufacturers" + 0.007*"active" + 0.006*"lived" + 0.006*"pension" + 0.006*"chemical" + 0.006*"suitable"'),
 (25,
  '0.046*"gas" + 0.024*"generation" + 0.020*"electric" + 0.018*"nuclear" + 0.017*"transmission" + 0.015*"utility" + 0.013*"electricity" + 0.010*"coal" + 0.010*"fuel" + 0.009*"recover"'),
 (26,
  '0.078*"consumers" + 0.035*"brands" + 0.015*"beverage" + 0.013*"retail" + 0.013*"brand" + 0.012*"publicity" + 0.010*"commerce" + 0.009*"retailers" + 0.008*"independent" + 0.008*"packaging"'),
 (27,
  '0.053*"institutions" + 0.013*"institution" + 0.012*"loan" + 0.011*"lending" + 0.009*"default" + 0.009*"loans" + 0.008*"servicing" + 0.008*"libor" + 0.008*"monetary" + 0.008*"beginning"'),
 (28,
  '0.038*"project" + 0.024*"prospects" + 0.019*"properties" + 0.015*"venture" + 0.011*"steel" + 0.010*"backlog" + 0.008*"complete" + 0.008*"construction" + 0.007*"estimated" + 0.007*"limits"'),
 (29,
  '0.027*"merger" + 0.013*"representations" + 0.013*"taxable" + 0.011*"opinion" + 0.010*"distributions" + 0.009*"separation" + 0.009*"qualify" + 0.009*"ruling" + 0.008*"free" + 0.008*"counsel"')]

## model evaluation

In [7]:
model_name = "gensim_0.05_0.5_30_0.05_0.01"

print(f"LDA model to be examined: {model_name}")

a=lda_eval_lib.metrics.IDXtopics2keep(savefolder,model_name)
print(f"proportion of valid topics: {a}")

b=lda_eval_lib.metrics.diversity(savefolder,model_name)
print(f"diversity score: {b}")

c=lda_eval_lib.metrics.granularity(savefolder,model_name)
print(f"granularity score: {c}")

d=lda_eval_lib.metrics.perplexity(savefolder,model_name)
print(f"perplexity score: {d}")

e=lda_eval_lib.metrics.coherence(savefolder,model_name)
print(f"coherence score: {e}")

LDA model to be examined: gensim_0.05_0.5_30_0.05_0.01
proportion of valid topics: 1.0
diversity score: 0.8
granularity score: 0.7072933333333333
perplexity score: -8.264980504326799
coherence score: 0.5784232405932289

#### GPT assisted tasks (WIT, labelling)

In [8]:
# ChatGPT assisted tasks
client = lda_eval_lib.util.OpenAI_client()

Enter your API key:  ········

In [9]:
top_n = 5
bottom_n = 0.15
common_n = 20
chunk_size = 3

# Define the model
gpt_model = "gpt-4o"
model_name = "gensim_0.05_0.5_30_0.05_0.01"

result = lda_eval_lib.gpt_wit.word_intrusion_task(savefolder,model_name, client, top_n, bottom_n, common_n, chunk_size=10,
                           gpt_model="gpt-4o", temperature=0)

In [10]:
result

,model_name,task,accuracy
0,gensim_0.05_0.5_30_0.05_0.01,Model Topic ...,0.866667

In [11]:
gpt_model = "gpt-4o"
model_name = 'gensim_0.05_0.5_30_0.05_0.01'
lda_eval_lib.gpt_labelling.labelling(savefolder, model_name, client, gpt_model)

Labels checked - overlapping labels identified!
Suggesting new labels...
Done!

,topic,label,rationale,keywords
0,Topic0,Legal Indemnification and Contractual Obligations,The keywords focus on legal aspects such as in...,"indemnification, raw, agreement, letter, rulin..."
1,Topic1,Digital Media Growth and Talent Acquisition,"The presence of keywords like digital, adverti...","digital, advertising, talent, incorporated, qu..."
2,Topic2,Patent Protection & Enforcement Risks,This topic centers on risks pertaining to the ...,"patents, patent, injury, post, monetary, infri..."
3,Topic3,Media Relations and Corporate Governance,The keywords hint at risks related to media ex...,"advertising, forum, stockholders, media, direc..."
4,Topic4,Oil and Gas Exploration and Commodity Risks,"With keywords like oil, gas, drilling, and exp...","oil, gas, drilling, reserves, rigs, exploratio..."
5,Topic5,Beverage Industry Operational Risks,The keywords suggest risks related to the oper...,"water, brands, raw, beverage, class, packaging..."
6,Topic6,Bank & Real Estate Related Financial Risks,The focus here is on financial sector-specific...,"loans, libor, loan, real, estate, banking, ban..."
7,Topic7,Retail and Store Management Risks,Keywords highlight risks associated with manag...,"stores, retail, inventory, retailers, lease, s..."
8,Topic8,Client Relationship and Fee-based Service Risks,This topic focuses on risks faced by service f...,"clients, client, solutions, fees, underwriting..."
9,Topic9,Emerging Technology and Communication Disrupti...,Keywords suggest risks related to technologica...,"pension, similarly, incidents, internet, intro..."
10,Topic10,Product Development and Inventory Management R...,The keywords focus on aspects of business tran...,"transformation, ventures, inventory, warranty,..."
11,Topic11,Customer Loyalty & Credit Card Operations Risks,This topic is centered on risks related to fin...,"cards, card, member, members, regulators, bran..."
12,Topic12,Aviation and Fuel Cost Risks,The words are centered around the aviation ind...,"aircraft, fuel, carriers, air, travel, airline..."
13,Topic13,Agricultural Commodity and Supply Chain Risks,"The keywords denote elements of agriculture, c...","ingredients, water, food, agricultural, commod..."
14,Topic14,Financial Instruments Valuation & Currency Hed...,This topic emphasizes risks associated with fi...,"curve, section, fair, valuation, denominated, ..."
15,Topic15,R&D and Engineering Intellectual Property Risks,This topic emphasizes risks linked to research...,"research, raw, manufacture, engineering, desig..."
16,Topic16,Fleet and Mobility Services Risks,The keywords pertain to risks associated with ...,"vehicles, vehicle, rental, fleet, locations, m..."
17,Topic17,Educational Institution Funding and Compliance...,The keywords are indicative of risks faced by ...,"institutions, institution, participate, title,..."
18,Topic18,Accounting Risks & Pension Liabilities,The focus here is on accounting and financial ...,"segment, note, compared, partially, fair, cont..."
19,Topic19,Medical Device Manufacturing and Regulatory Risks,The keywords are associated with risks in the ...,"care, medical, clinical, healthcare, reimburse..."
20,Topic20,Software and Cloud Licensing Risks,"The keywords focus on software solutions, clou...","software, solutions, cloud, licenses, distribu..."
21,Topic21,Budget Management & Defense Contracting Risks,This topic covers the risks surrounding the fi...,"profits, budget, productivity, segment, raw, s..."
22,Topic22,Shareholder and Voting Rights Risks,"Keywords such as shares, shareholders, voting,...","shares, properties, preferred, holders, shareh..."
23,Topic23,Resource and Labor Shortages Risks,"The terms fuel, pension, wage, employment, and...","fuel, pension, currencies, goods, wage, employ..."
24,Topic24,Supply Chain Operational & Patent Risks,This topic covers potential risks in supply ch...,"raw, dealers, hazardous, patents, manufacturer..."
25,Topic25,Energy Generation and Supply Chain Risks,The keywords focus on various facets of energy...,"gas, generation, electric, nuclear, transmissi..."
26,Topic26,Consumer Goods and Brand Management Risks,The keywords revolve around consumer-facing as...,"consumers, brands, beverage, retail, brand, pu..."
27,Topic27,Creditworthiness & Loan Servicing Risks,This topic indicates the risks associated with...,"institutions, institution, loan, lending, defa..."
28,Topic28,Construction Project and Venture Development R...,The keywords reflect elements of large-scale p...,"project, prospects, properties, venture, steel..."
29,Topic29,Corporate Restructuring and Taxation Risks,The keywords focus on corporate restructuring ...,"merger, representations, taxable, opinion, dis..."

### Visualization

In [12]:
import pyLDAvis

pyldavisdata = lda_eval_lib.custom_pyvis.visualize_topics(savefolder, model_name)

# Apply pyLDAvis
vis_data= pyLDAvis.prepare(**pyldavisdata, R=30, n_jobs = -1, mds='mmds', sort_topics=False)

pyLDAvis.display(vis_data)

In [296]:
# save the result
pyLDAvis.save_html(vis_data, '/Users/gitaepark/Downloads/output_filename.html')