# Example

In [1]:
import lda_eval_lib
import pandas as pd
import os

In [2]:
# Load a test file
package_path = os.path.dirname(lda_eval_lib.__file__)
data_path = os.path.join(package_path, 'test', 'test_text.pkl')
item1a = pd.read_pickle(data_path)
tokenized_text = item1a['text4LDA']

### LDA run (gensim LDA and modified mallet wrapper)

In [3]:

# Set parameters
minpc = 0.05 
maxpc = 0.5
alpha = 0.05
beta = 0.01
ntopics = 30

# path to mallet bin
mallet_path = '/Users/mallet-2.0.8/bin/mallet'

# path to save models
savefolder = '/Users/Result'

In [11]:
lda_eval_lib.lda_model.lda_run(tokenized_text, minpc, maxpc, alpha, beta, ntopics, mallet_path, savefolder, gensimpasses = 500, gensimiterations = 500, malletiterations = 1000)

 - modelling  gensim_0.05_0.5_30_0.05_0.01
model saved: /Users/gitaepark/Downloads/gensim_0.05_0.5_30_0.05_0.01
 - modelling  mallet_0.05_0.5_30_0.05_0.01

Mallet LDA: 30 topics, 5 topic bits, 11111 topic mask
Data loaded.
max tokens: 3423
total tokens: 512341
<10> LL/token: -8.81413
<20> LL/token: -8.09392
<30> LL/token: -7.9286
<40> LL/token: -7.85225
<50> LL/token: -7.80223
<60> LL/token: -7.76484
<70> LL/token: -7.74077
<80> LL/token: -7.72202
<90> LL/token: -7.70379
<100> LL/token: -7.68813
<110> LL/token: -7.67527
<120> LL/token: -7.66288
<130> LL/token: -7.65012
<140> LL/token: -7.64321
<150> LL/token: -7.6323
<160> LL/token: -7.62273
<170> LL/token: -7.61566
<180> LL/token: -7.61162
<190> LL/token: -7.60661
<200> LL/token: -7.60062
<210> LL/token: -7.59649
<220> LL/token: -7.59346
<230> LL/token: -7.5896
<240> LL/token: -7.58427
<250> LL/token: -7.58237
<260> LL/token: -7.57615
<270> LL/token: -7.57504
<280> LL/token: -7.57152
<290> LL/token: -7.57001
<300> LL/token: -7.56959
<310> LL/token: -7.56808
<320> LL/token: -7.56613
<330> LL/token: -7.56646
<340> LL/token: -7.5659
<350> LL/token: -7.55694
<360> LL/token: -7.55606
<370> LL/token: -7.55435
<380> LL/token: -7.55411
<390> LL/token: -7.54993
<400> LL/token: -7.55039
<410> LL/token: -7.54482
<420> LL/token: -7.54369
<430> LL/token: -7.54092
<440> LL/token: -7.5395
<450> LL/token: -7.53735
<460> LL/token: -7.53541
<470> LL/token: -7.53315
<480> LL/token: -7.53202
<490> LL/token: -7.53233
<500> LL/token: -7.52935
<510> LL/token: -7.52953
<520> LL/token: -7.52496
<530> LL/token: -7.52484
<540> LL/token: -7.52303
<550> LL/token: -7.52039
<560> LL/token: -7.51565
<570> LL/token: -7.51994
<580> LL/token: -7.51627
<590> LL/token: -7.51617
<600> LL/token: -7.5144
<610> LL/token: -7.5167
<620> LL/token: -7.51308
<630> LL/token: -7.51548
<640> LL/token: -7.51526
<650> LL/token: -7.50816
<660> LL/token: -7.51097
<670> LL/token: -7.5119
<680> LL/token: -7.51124
<690> LL/token: -7.5106
<700> LL/token: -7.51032
<710> LL/token: -7.50932
<720> LL/token: -7.51151
<730> LL/token: -7.51111
<740> LL/token: -7.51389
<750> LL/token: -7.51153
<760> LL/token: -7.51062
<770> LL/token: -7.51169
<780> LL/token: -7.513
<790> LL/token: -7.51039
<800> LL/token: -7.5093
<810> LL/token: -7.50859
<820> LL/token: -7.51165
<830> LL/token: -7.50895
<840> LL/token: -7.50892
<850> LL/token: -7.51088
<860> LL/token: -7.50793
<870> LL/token: -7.51107
<880> LL/token: -7.50906
<890> LL/token: -7.5077
<900> LL/token: -7.50529
<910> LL/token: -7.50693
<920> LL/token: -7.50518
<930> LL/token: -7.50423
<940> LL/token: -7.5029
<950> LL/token: -7.5018
<960> LL/token: -7.50553
<970> LL/token: -7.50324
<980> LL/token: -7.50511
<990> LL/token: -7.5043
<1000> LL/token: -7.50398

Total time: 39 seconds

model saved: /Users/gitaepark/Downloads/mallet_0.05_0.5_30_0.05_0.01

In [13]:
# Load the stored model
lda_model, textbeforetokenization, tokenized_text, corpus, id2word = lda_eval_lib.util.load_lda_run(savefolder,model_name)

# lda_model is other gensim.lda object or gensim.mallet object
lda_model.show_topics(num_topics=-1)

[(0,
  '0.033*"software" + 0.015*"solutions" + 0.010*"distributors" + 0.008*"licenses" + 0.007*"cloud" + 0.006*"incidents" + 0.006*"license" + 0.005*"technical" + 0.005*"infringement" + 0.005*"channel"'),
 (1,
  '0.029*"segment" + 0.021*"note" + 0.019*"fair" + 0.015*"compared" + 0.015*"partially" + 0.013*"continuing" + 0.013*"unit" + 0.012*"refer" + 0.012*"recognized" + 0.012*"versus"'),
 (2,
  '0.057*"aircraft" + 0.028*"travel" + 0.027*"air" + 0.026*"fuel" + 0.026*"carriers" + 0.025*"airline" + 0.021*"airlines" + 0.009*"traffic" + 0.009*"agreement" + 0.008*"fees"'),
 (3,
  '0.032*"shares" + 0.026*"properties" + 0.017*"shareholders" + 0.013*"real" + 0.013*"voting" + 0.012*"lease" + 0.012*"preferred" + 0.011*"libor" + 0.010*"estate" + 0.009*"vote"'),
 (4,
  '0.079*"gas" + 0.071*"oil" + 0.027*"reserves" + 0.016*"crude" + 0.016*"drilling" + 0.012*"water" + 0.011*"properties" + 0.010*"commodity" + 0.010*"wells" + 0.009*"exploration"'),
 (5,
  '0.007*"care" + 0.007*"clinical" + 0.006*"reimbursement" + 0.006*"clearance" + 0.006*"monetary" + 0.005*"collaborative" + 0.005*"medical" + 0.005*"license" + 0.005*"ventures" + 0.004*"indemnification"'),
 (6,
  '0.025*"generation" + 0.024*"transmission" + 0.023*"nuclear" + 0.022*"prospects" + 0.019*"gas" + 0.014*"fuel" + 0.013*"project" + 0.012*"applies" + 0.011*"electric" + 0.011*"electricity"'),
 (7,
  '0.022*"healthcare" + 0.008*"manufacture" + 0.008*"patents" + 0.008*"medical" + 0.008*"reimbursement" + 0.007*"agreement" + 0.007*"patent" + 0.006*"separation" + 0.006*"payers" + 0.005*"raw"'),
 (8,
  '0.025*"brands" + 0.022*"beverage" + 0.021*"consumers" + 0.019*"packaging" + 0.016*"water" + 0.013*"raw" + 0.010*"brand" + 0.009*"retailers" + 0.009*"ingredients" + 0.008*"retail"'),
 (9,
  '0.047*"drilling" + 0.032*"rigs" + 0.024*"oil" + 0.018*"shares" + 0.017*"gas" + 0.014*"offshore" + 0.010*"termination" + 0.010*"shareholders" + 0.008*"exploration" + 0.007*"ordinary"'),
 (10,
  '0.013*"raw" + 0.011*"patents" + 0.007*"commodity" + 0.007*"manufacturers" + 0.006*"manufacture" + 0.006*"external" + 0.006*"patent" + 0.006*"logistics" + 0.006*"chemical" + 0.005*"inventory"'),
 (11,
  '0.038*"loans" + 0.017*"loan" + 0.015*"banking" + 0.013*"bank" + 0.013*"real" + 0.012*"libor" + 0.011*"banks" + 0.011*"estate" + 0.009*"deposits" + 0.008*"mortgage"'),
 (12,
  '0.022*"pension" + 0.013*"venture" + 0.010*"steel" + 0.009*"raw" + 0.008*"contributions" + 0.007*"deferred" + 0.007*"hazardous" + 0.006*"defined" + 0.005*"fixed" + 0.005*"complete"'),
 (13,
  '0.030*"medical" + 0.028*"care" + 0.014*"devices" + 0.013*"tests" + 0.011*"device" + 0.010*"approval" + 0.010*"testing" + 0.009*"manufacture" + 0.008*"clinical" + 0.008*"reimbursement"'),
 (14,
  '0.051*"vehicles" + 0.029*"vehicle" + 0.021*"rental" + 0.017*"fleet" + 0.013*"locations" + 0.008*"fuel" + 0.008*"operators" + 0.008*"travel" + 0.008*"truck" + 0.007*"backed"'),
 (15,
  '0.022*"shares" + 0.014*"holders" + 0.010*"covenants" + 0.009*"agreement" + 0.007*"ii" + 0.007*"assure" + 0.006*"directors" + 0.006*"construction" + 0.006*"members" + 0.006*"repurchase"'),
 (16,
  '0.021*"cards" + 0.019*"card" + 0.015*"members" + 0.013*"member" + 0.011*"brand" + 0.010*"acceptance" + 0.009*"regulators" + 0.009*"travel" + 0.007*"loans" + 0.006*"discount"'),
 (17,
  '0.102*"clients" + 0.034*"client" + 0.025*"institutions" + 0.016*"institution" + 0.014*"participate" + 0.011*"iv" + 0.011*"title" + 0.010*"eligibility" + 0.008*"education" + 0.007*"lose"'),
 (18,
  '0.031*"merger" + 0.012*"taxable" + 0.012*"distributions" + 0.011*"representations" + 0.011*"separation" + 0.011*"ruling" + 0.010*"qualify" + 0.008*"free" + 0.008*"opinion" + 0.008*"opinions"'),
 (19,
  '0.013*"dealers" + 0.009*"inventory" + 0.008*"marine" + 0.008*"fuel" + 0.008*"supplier" + 0.008*"engine" + 0.007*"engines" + 0.006*"separation" + 0.006*"raw" + 0.006*"goods"'),
 (20,
  '0.035*"clinical" + 0.022*"approval" + 0.021*"trials" + 0.018*"drug" + 0.016*"candidates" + 0.015*"manufacturers" + 0.014*"approved" + 0.013*"reimbursement" + 0.013*"patients" + 0.013*"pharmaceutical"'),
 (21,
  '0.017*"institutions" + 0.013*"yen" + 0.012*"denominated" + 0.011*"libor" + 0.009*"rating" + 0.008*"derivatives" + 0.008*"section" + 0.007*"instruments" + 0.006*"relies" + 0.006*"operates"'),
 (22,
  '0.032*"gas" + 0.022*"transmission" + 0.020*"generation" + 0.016*"nuclear" + 0.014*"electricity" + 0.013*"electric" + 0.013*"utility" + 0.011*"coal" + 0.009*"plants" + 0.008*"construction"'),
 (23,
  '0.042*"gas" + 0.031*"electric" + 0.023*"utility" + 0.017*"consumers" + 0.015*"generation" + 0.013*"commodity" + 0.010*"postretirement" + 0.010*"generating" + 0.009*"electricity" + 0.009*"coal"'),
 (24,
  '0.009*"disaster" + 0.008*"frequently" + 0.007*"licenses" + 0.007*"wireless" + 0.007*"vendor" + 0.007*"regulators" + 0.007*"fees" + 0.006*"communications" + 0.006*"mix" + 0.006*"internet"'),
 (25,
  '0.013*"raw" + 0.008*"research" + 0.008*"improper" + 0.007*"incidents" + 0.007*"digital" + 0.007*"emerging" + 0.006*"solutions" + 0.006*"software" + 0.006*"manufacture" + 0.006*"monetary"'),
 (26,
  '0.022*"project" + 0.018*"subcontractors" + 0.015*"profits" + 0.013*"budget" + 0.012*"suspension" + 0.012*"segment" + 0.011*"backlog" + 0.011*"contractor" + 0.010*"contractors" + 0.010*"termination"'),
 (27,
  '0.045*"advertising" + 0.031*"stations" + 0.026*"media" + 0.023*"programming" + 0.019*"digital" + 0.016*"content" + 0.015*"merger" + 0.011*"spin" + 0.010*"shareholders" + 0.010*"communications"'),
 (28,
  '0.009*"underwriting" + 0.009*"care" + 0.008*"consulting" + 0.007*"premiums" + 0.007*"brokers" + 0.007*"premium" + 0.007*"utilities" + 0.007*"brokerage" + 0.006*"attack" + 0.006*"judgment"'),
 (29,
  '0.008*"solutions" + 0.006*"claim" + 0.005*"stockholders" + 0.005*"lose" + 0.005*"integration" + 0.005*"transition" + 0.005*"grow" + 0.004*"directors" + 0.004*"quickly" + 0.004*"technical"')]

## model evaluation

In [12]:
savefolder = '/Users/Result'
model_name = "mallet_0.05_0.5_30_0.05_0.01"

print(f"LDA model to be examined: {model_name}")

a=lda_eval_lib.metrics.IDXtopics2keep(savefolder,model_name)
print(f"proportion of valid topics: {a}")

b=lda_eval_lib.metrics.diversity(savefolder,model_name)
print(f"diversity score: {b}")

c=lda_eval_lib.metrics.granularity(savefolder,model_name)
print(f"granularity score: {c}")

d=lda_eval_lib.metrics.perplexity(savefolder,model_name)
print(f"perplexity score: {d}")

e=lda_eval_lib.metrics.coherence(savefolder,model_name)
print(f"coherence score: {e}")

LDA model to be examined: mallet_0.05_0.5_30_0.05_0.01
proportion of valid topics: 1.0
diversity score: 0.72
granularity score: 0.7108999999999999
perplexity score: -7.291902808369964
coherence score: 0.5725893960168911

#### GPT assisted tasks (WIT, labelling)

In [3]:
# ChatGPT assisted tasks
client = lda_eval_lib.util.OpenAI_client()

Enter your API key:  ········

In [14]:
top_n = 5
bottom_n = 0.15
common_n = 20
chunk_size = 3

# Define the model
gpt_model = "gpt-4o"
savefolder = '/Users/gitaepark/Downloads'
model_name = 'mallet_0.05_0.5_30_0.05_0.01'


result = lda_eval_lib.gpt_wit.word_intrusion_task(savefolder,model_name, client, top_n, bottom_n, common_n, chunk_size=10,
                           gpt_model="gpt-4o", temperature=0)

In [19]:
result

,model_name,task,accuracy
0,gensim_0.05_0.4_20_0.01_0.01,Model Topic ...,0.5

In [4]:
gpt_model = "gpt-4o"
savefolder = '/Users/gitaepark/Downloads'
model_name = 'mallet_0.05_0.5_30_0.05_0.01'
lda_eval_lib.gpt_labelling.labelling(savefolder, model_name, client, gpt_model)

Labels checked - overlapping labels identified!
Suggesting new labels...
Done!

,topic,label,rationale,keywords
0,Topic0,Software Licensing and Distribution Risks,The keywords indicate concerns related to soft...,"software, solutions, distributors, licenses, c..."
1,Topic1,Financial Reporting and Segment Analysis,The keywords focus on financial reporting aspe...,"segment, note, fair, compared, partially, cont..."
2,Topic2,Aviation Industry Operational Risks,The keywords reflect operational risks within ...,"aircraft, travel, air, fuel, carriers, airline..."
3,Topic3,Real Estate and Shareholder Equity Risks,The keywords denote risks related to real esta...,"shares, properties, shareholders, real, voting..."
4,Topic4,Oil and Gas Resources Exploration Risks,"Based on the keywords, this label emphasizes t...","gas, oil, reserves, crude, drilling, water, pr..."
5,Topic5,Healthcare Reimbursement and Compliance Risks,The keywords suggest a focus on the healthcare...,"care, clinical, reimbursement, clearance, mone..."
6,Topic6,Energy Production and Transmission Risks,This label refers to the risks associated with...,"generation, transmission, nuclear, prospects, ..."
7,Topic7,Pharmaceutical Manufacturing and Intellectual ...,This topic centers around the healthcare and p...,"healthcare, manufacture, patents, medical, rei..."
8,Topic8,Consumer Goods Branding and Retail Risks,The keywords relate to the consumer goods indu...,"brands, beverage, consumers, packaging, water,..."
9,Topic9,Oil and Gas Industry and Shareholder Financial...,The words 'shares' and 'shareholders' suggest ...,"drilling, rigs, oil, shares, gas, offshore, te..."
10,Topic10,Raw Materials and Patent Logistics,The keywords suggest a focus on the supply cha...,"raw, patents, commodity, manufacturers, manufa..."
11,Topic11,Financial Sector and Interest Rate Risks,"Keywords point to the financial industry, spec...","loans, loan, banking, bank, real, libor, banks..."
12,Topic12,Pension and Hazardous Materials Risks,The presence of both pension and hazardous mat...,"pension, venture, steel, raw, contributions, h..."
13,Topic13,Medical Device Approval and Compliance,"The keywords revolve around medical devices, e...","medical, care, devices, tests, device, approva..."
14,Topic14,Vehicle Fleet and Rental Market Dynamics,The focus is on vehicles and the logistics of ...,"vehicles, vehicle, rental, fleet, locations, f..."
15,Topic15,Shareholder Agreements and Corporate Governance,"The keywords indicate a focus on shareholders,...","shares, holders, covenants, agreement, assure,..."
16,Topic16,Credit and Payment Systems Risks,"The presence of words such as 'cards', 'member...","cards, card, members, member, brand, acceptanc..."
17,Topic17,Client Engagement and Institutional Relations,The keywords highlight client and institutiona...,"clients, client, institutions, institution, pa..."
18,Topic18,Taxable Merger and Corporate Restructuring,"Keywords like 'merger', 'taxable', 'separation...","merger, distributions, taxable, representation..."
19,Topic19,Supply Chain and Inventory Management in Marit...,"The presence of 'dealers', 'inventory', 'marin...","dealers, inventory, marine, fuel, supplier, en..."
20,Topic20,Pharmaceutical Drug Development Risks,The keywords suggest a focus on the pharmaceut...,"clinical, approval, trials, drug, candidates, ..."
21,Topic21,Financial Instruments and Foreign Exchange Risks,The keywords indicate concerns related to fina...,"institutions, yen, denominated, libor, rating,..."
22,Topic22,Energy Infrastructure and Powerplants Risks,The new label focuses on the structural compon...,"gas, transmission, generation, nuclear, electr..."
23,Topic23,Utility and Commodity Market Risks,"The emphasis here is on the utility sector, sp...","gas, electric, utility, consumers, generation,..."
24,Topic24,Telecommunications Licensing and Regulatory Risks,Keywords point to risks in the telecommunicati...,"disaster, frequently, licenses, wireless, vend..."
25,Topic25,Emerging Digital Solutions and Research Risks,This topic revolves around potential risks ass...,"raw, research, improper, digital, incidents, e..."
26,Topic26,Project Management and Contractual Risks,The focus here is on risks associated with man...,"project, subcontractors, profits, budget, susp..."
27,Topic27,Media and Communications Mergers and Acquisiti...,"This topic addresses risks linked to mergers, ...","advertising, stations, media, programming, dig..."
28,Topic28,Insurance and Brokerage Judgment Risks,The keywords suggest risks associated with the...,"underwriting, care, consulting, premiums, brok..."
29,Topic29,Integration and Transition Risks in Technical ...,This topic is centered around the risks of int...,"solutions, claim, stockholders, lose, integrat..."

### Visualization

In [16]:
import pyLDAvis

pyldavisdata = lda_eval_lib.custom_pyvis.visualize_topics(savefolder, model_name)

# Apply pyLDAvis
vis_data= pyLDAvis.prepare(**pyldavisdata, R=30, n_jobs = -1, mds='mmds', sort_topics=False)

pyLDAvis.display(vis_data)

/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/internals/blocks.py:393: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)
/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/internals/blocks.py:393: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)
/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/internals/blocks.py:393: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)

In [296]:
# save the result
pyLDAvis.save_html(vis_data, '/Users/gitaepark/Downloads/output_filename.html')